### ISSUE TITLE
Will questions/scenarios be available?

### ISSUE THREAD

**Issue by ChrisYounger** [daveherrald/botsv1#1]
Thanks for releasing this data set. 

Will the 'questions' (scenarios?) from the v1 BOTS be released at some point?

**Comment by daveherrald** [comment]
Hi Chris! Thanks for your interest. Yes we do plan to release the questions/answers but no timetable just yet. More to come, hopefully soon.

**Comment by daveherrald** [comment]
Chris, questions, answers, and hints are available now. Just email bots@splunk.com and we will get them to you.
