### ISSUE TITLE
botsv1_data_set  import

### ISSUE THREAD

**Issue by wisekhan** [daveherrald/botsv1#4]
how can I use botsv1_data_set(6 GB dataset)  into splunk?
Do I need botsv1_data_set app for this?

Best REGARDS

**Comment by gsinjari** [comment]
After you install all apps mentioned in the instruction, you can install "botsv1_data_set.tgz" by using this command:
$SPLUNK_HOME/splunk install app /pathtofile/botsv1_data_set.tgz
