### ISSUE TITLE
attack data in  BOTS v1 Dataset

### ISSUE THREAD

**Issue by wstart** [daveherrald/botsv1#5]
how can i Identifi an attact data in json src?
for ex: in  stream:http | https://s3.amazonaws.com/botsv1/json-by-sourcetype/botsv1.stream-http.json.gz
 
which Field in  the json show it is attack data ?

**Comment by daveherrald** [comment]
I recommend using the pre-indexed Splunk version of the data. It will be far easier to search that way.
