### ISSUE TITLE
botsv1-attack-only.tgz not working

### ISSUE THREAD

**Issue by petetiR** [daveherrald/botsv1#6]
Hello,

First of all, thank you for making this challenge accessible to us.
However, I can not install the botsv1-attack-only version of the data set.

Here's the output I recieved from the console :
```console
C:\Program Files\bin>splunk install app D:\botsv1-attack-only.tgz
Invalid app contents: archive contains more than one immediate subdirectory:  and botsv1.dat
```
Any ideas ?

**Comment by daveherrald** [comment]
@petetiR thanks for reporting this. I was able to reproduce it and I believe it is fixed now. Can you download and try again? 

Note this repository has moved to https://github.com/splunk/botsv1
